Add Arch Linux instructions
sorairolake/qrtool pull request #509
Opened 2024-06-14 13:27 UTC by orhun

## Description

`qrtool` is now packaged in the official Arch Linux repositories: <https://archlinux.org/packages/extra/x86_64/qrtool/> 🥳

## Checklist

- [x] I have read the [Contribution Guide].
- [x] I agree to follow the [Code of Conduct].

[Contribution Guide]: https://github.com/sorairolake/qrtool/blob/develop/CONTRIBUTING.adoc
[Code of Conduct]: https://github.com/sorairolake/qrtool/blob/develop/CODE_OF_CONDUCT.md

2024-06-14 16:36 UTC, sorairolake commented on README.md
> -
Don't remove this blank line.

<https://prettier.io/blog/2024/06/01/3.3.0#add-newline-between-markdown-footnote-definitions-16063httpsgithubcomprettierprettierpull16063-by-atemahttpsgithubcomatema>

2024-06-14 16:40 UTC, sorairolake commented on README.md
> +| [_Arch Linux_] | [Pacman]        | `pacman -S qrtool`                    |
```suggestion
| [_Arch Linux_] | [Pacman]        | `pacman -S qrtool`                    |
| [_openSUSE_]   | Zypper          | `zypper install qrtool`               |
```

2024-06-14 16:41 UTC, sorairolake commented on README.md
> +[Pacman]: https://wiki.archlinux.org/title/pacman
```suggestion
[_Arch Linux_]: https://archlinux.org/
[Pacman]: https://wiki.archlinux.org/title/pacman
[_openSUSE_]: https://www.opensuse.org/
```

2024-06-14 16:50 UTC, sorairolake requested changes
Thanks for your contribution!

2024-06-14 16:57 UTC, sorairolake commented
If possible, please do the following:

```sh
reuse annotate -c "<YOUR NAME>" -y "<YEAR>" README.md
```

https://github.com/fsfe/reuse-tool

2024-06-15 03:58 UTC, sorairolake approved these changes

2024-06-15 04:06 UTC, merged

2025-05-07 16:26 UTC, sorairolake commented
@orhun I've changed the license for `README.md` from `Apache-2.0 OR MIT` to `CC-BY-4.0` in 5605625. This file contains your contributions. Please tell me if you agree to this license change. If you disagree with this, I'll revert the license of `README.md` to `Apache-2.0 OR MIT`.

2025-05-07 17:27 UTC, orhun commented
That's fine by me 👍🏼

2025-05-07 17:31 UTC, sorairolake commented
Thanks!